[build]
functions = "server/netlify/functions"
command = "npm run build"
publish = "client/dist"

[functions]
directory = "server/netlify/functions"
external_node_modules = ["express"]
node_bundler = "esbuild"

# Redirect API requests to serverless functions
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[dev]
publish = "client/dist"
functions = "server/netlify/functions"

[build.environment]
NODE_VERSION = "22.11.0"
USE_NETLIFY_LARGE_MEDIA=true

[context.production.environment]
NODE_ENV = "production"

[context.deploy-preview.environment]
NODE_ENV = "development"
