[build]
  command = "npm run build"
  publish = "client/dist"


[functions]
  directory = "server"
  included_files = ["server/**/*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

