[build]
  functions = "server/netlify/functions"
  command = "npm run build"
  publish = "client/dist"

[functions]
  directory="server/netlify/functions"
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
[dev]
  publish = "server"
  directory = "server"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.11.0"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"