[build]
  functions = "server/netlify/functions"
  functionsDirectory = "serever/netlify/functions"
  command = "npm run build"
  publish = "client/dist"

[dev]
  publish = "server"
  directory = "server"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "22.11.0"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"