[build]
  functions = "functions"
  functionsDirectory = "netlify/functions"
  command = "npm run build"
  publish = "client/dist"

[dev]
  publish = "server"
  directory = "server"
  functions = "functions"

[build.environment]
  NODE_VERSION = "14"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"